export const playersColors = [
    {
        name:'blue',
        primaryColor:'#2E75B6',
        secondaryColor:'#0996FF',
        textColor:'#FFFFFF',
    },
    {
        name:'red',
        primaryColor:'#FF0000',
        secondaryColor:'#FF7C80',
        textColor:'#FFFFFF',
    },
    {
        name:'white',
        primaryColor:'#FFFFFF',
        secondaryColor:'#EFEBD8',
        textColor:'#000000',
    },
    {
        name:'yellow',
        primaryColor:'#FFC000',
        secondaryColor:'#FFE593',
        textColor:'#000000',
    }
]