export const CURRENT_USER = "CURRENT_USER";

export const GET_USER_GAMES_REQUEST = "GET_USER_GAMES_REQUEST";
export const GET_USER_GAMES_SUCCESS = "GET_USER_GAMES_SUCCESS";
export const GET_USER_GAMES_ERROR = "GET_USER_GAMES_ERROR";

export const GET_BUILD_SETTELMENT_REQUEST = "GET_BUILD_SETTELMENT_REQUEST";
export const GET_BUILD_SETTELMENT_SUCCESS = "GET_BUILD_SETTELMENT_SUCCESS";
export const GET_BUILD_SETTELMENT_ERROR = "GET_BUILD_SETTELMENT_ERROR";

export const GET_BUILD_CITY_REQUEST = "GET_BUILD_CITY_REQUEST";
export const GET_BUILD_CITY_SUCCESS = "GET_BUILD_CITY_SUCCESS";
export const GET_BUILD_CITY_ERROR = "GET_BUILD_CITY_ERROR";

export const GET_BUILD_ROAD_REQUEST = "GET_BUILD_ROAD_REQUEST";
export const GET_BUILD_ROAD_SUCCESS = "GET_BUILD_ROAD_SUCCESS";
export const GET_BUILD_ROAD_ERROR = "GET_BUILD_ROAD_ERROR";

export const SET_BOARD_GAME_DIMS = "BOARD_GAME_DIMS";

export const CREATE_NEW_GAME_REQUEST = "CREATE_NEW_GAME_REQUEST";
export const CREATE_NEW_GAME_SUCCESS = "CREATE_NEW_GAME_SUCCESS";
export const CREATE_NEW_GAME_ERROR = "CREATE_NEW_GAME_ERROR";

export const GET_GAME_DATA_SUCCESS = "GET_GAME_DATA_SUCCESS";
export const GET_GAME_DATA_ERROR =   "GET_GAME_DATA_ERROR";
export const GET_GAME_DATA_REQUEST = "GET_GAME_DATA_REQUEST";

export const GET_VALID_ACTIONS_SUCCESS = "GET_VALID_ACTIONS_SUCCESS";
export const GET_VALID_ACTIONS_ERROR =   "GET_VALID_ACTIONS_ERROR";
export const GET_VALID_ACTIONS_REQUEST = "GET_VALID_ACTIONS_REQUEST";

export const SET_CURRENT_ACTION_SUCCESS = "SET_CURRENT_ACTION_SUCCESS";
export const SET_CURRENT_ACTION_ERROR =   "SET_CURRENT_ACTION_ERROR";
export const SET_CURRENT_ACTION_REQUEST = "SET_CURRENT_ACTION_REQUEST";

export const END_TURN_SUCCESS = "END_TURN_SUCCESS";
export const END_TURN_ERROR =   "END_TURN_ERROR";
export const END_TURN_REQUEST = "END_TURN_REQUEST";

export const DISTRIBUTE_RESOURCES_SUCCESS = "DISTRIBUTE_RESOURCES_SUCCESS";
export const DISTRIBUTE_RESOURCES_ERROR =   "DISTRIBUTE_RESOURCES_ERROR";
export const DISTRIBUTE_RESOURCES_REQUEST = "DISTRIBUTE_RESOURCES_REQUEST";

export const PLACE_ROBBER_SUCCESS = "PLACE_ROBBER_SUCCESS";
export const PLACE_ROBBER_ERROR =   "PLACE_ROBBER_ERROR";
export const PLACE_ROBBER_REQUEST = "PLACE_ROBBER_REQUEST";

export const BUY_DEVELOPMENT_CARD_SUCCESS = "BUY_DEVELOPMENT_CARD_SUCCESS";
export const BUY_DEVELOPMENT_CARD_ERROR =   "BUY_DEVELOPMENT_CARD_ERROR";
export const BUY_DEVELOPMENT_CARD_REQUEST = "BUY_DEVELOPMENT_CARD_REQUEST";

export const ACTIVATE_KNIGHT_CARD_SUCCESS = "ACTIVATE_KNIGHT_CARD_SUCCESS";
export const ACTIVATE_KNIGHT_CARD_ERROR =   "ACTIVATE_KNIGHT_CARD_ERROR";
export const ACTIVATE_KNIGHT_CARD_REQUEST = "ACTIVATE_KNIGHT_CARD_REQUEST";




